### ISSUE TITLE
Tags not updated because remote changed

### ISSUE THREAD

**Issue by Weakky** [prisma-labs/dripip#35]
## Description

We moved `nexus-prisma` to the graphql-nexus. When using `dripip stable`, git crashed because of the following error:

![image](https://user-images.githubusercontent.com/25233379/73642846-b976ad00-4672-11ea-9fbc-fc3cd4efb67c.png)

Result: `latest` and `next` tag weren't updated

I'm not sure what we can do about it, but thought it was still worth mentioning

**Comment by jasonkuhrt** [comment]
Looks like your clone of `nexus-prisma` is from a while back when it was located at `https://github.com/prisma-graphql/nexus-prisma`? Doesn't change your point anyways.

**Comment by jasonkuhrt** [comment]
I couldn't reproduce tonight:

```
~/projects/prisma-labs/dripip-test master
❯ gc --allow-empty -m 'fix: fake work'
[master bce4d55] fix: fake work

~/projects/prisma-labs/dripip-test master ⇡
❯ gp                                  
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 186 bytes | 186.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0)
remote: This repository moved. Please use the new location:
remote:   git@github.com:prisma-labs/dripip-test.git
To github.com:jasonkuhrt/dripip-test.git
   19a1396..bce4d55  master -> master

~/projects/prisma-labs/dripip-test master
❯ yarn -s dripip preview --skip-npm
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
reverted package.json changes now that publishing is done
tagged this commit with 0.0.4-next.1
pushed tag to remote
updated git-tag "next"

~/projects/prisma-labs/dripip-test master 12s
❯ yarn -s dripip stable --skip-npm
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
reverted package.json changes now that publishing is done
tagged this commit with 0.0.4
pushed tag to remote
updated git-tags "latest" "next"
```

Let's keep reporting on this issue. If it happened on `nexus-prisma` the other day, then presumably it will again the next time...

**Comment by jasonkuhrt** [comment]
Happened again, not because remote changed. Don't get it still.

![image](https://user-images.githubusercontent.com/284476/74751636-8d932400-523b-11ea-8947-bec717b23f96.png)
