### ISSUE TITLE
Failed to update git tags

### ISSUE THREAD

**Issue by Weakky** [prisma-labs/dripip#52]
## Description

![image](https://user-images.githubusercontent.com/25233379/75766301-3a43ca00-5d41-11ea-96dc-06ab743733e4.png)

**Comment by Weakky** [comment]
Oh. My bad. Didn't see we're now automatically publishing to the next tag when pushing on trunk (on `nexus-future`). That's why the tag already existed 🙈

**Comment by jasonkuhrt** [comment]
It looks like you were using an older version of `dripip` though. Tags are force pushed now. The error I see here is not about npm registry already having having `0.10.0-next.13` published.
